#!/usr/bin/env python3
"""Generate smaller WebP renditions of every image the site references, for srcset.

    python3 scripts/make-image-variants.py

Why: day-card images on the itinerary pages render at most 576 CSS px wide (342 on a
phone) but used to download 1920px originals — 3.4 MB of images on the B2 page alone.
For each raster under public/img that the source references and that is wider than a
target width, this writes <stem>-<width>.webp next to it (640, 800 and 1200 px, cwebp q80;
800 fits the ~380px three-column cards on a 2x screen),
and emits lib/imageVariants.generated.ts mapping the original URL to a ready srcset.

Originals are never modified: they are served with a one-year `immutable` cache, so
changing their bytes under the same name would not reach returning visitors anyway.
Re-run after adding or replacing images, and commit the variants plus the .ts file.
Needs Pillow and cwebp (brew install webp). Output is committed, so CI needs neither.
"""
import json
import re
import subprocess
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
OUT_TS = ROOT / "lib" / "imageVariants.generated.ts"
WIDTHS = (640, 800, 1200)
QUALITY = "80"
SOURCES = ["pages", "components", "i18n", "lib", "constants.tsx", "translations.ts", "App.tsx"]
REF = re.compile(r"""['"`](/img/[^'"`?#\s]+\.(?:webp|jpe?g|png))['"`]""")
VARIANT_NAME = re.compile(r"-\d{3,4}\.webp$")


def referenced_images() -> set[str]:
    refs: set[str] = set()
    for entry in SOURCES:
        path = ROOT / entry
        files = [path] if path.is_file() else list(path.rglob("*.ts*"))
        for f in files:
            if f.name == OUT_TS.name:
                continue
            refs.update(REF.findall(f.read_text(encoding="utf-8")))
    return {r for r in refs if not VARIANT_NAME.search(r)}


def main() -> None:
    manifest: dict[str, str] = {}
    made = kept = 0
    for url in sorted(referenced_images()):
        src = PUBLIC / url.lstrip("/")
        if not src.is_file():
            print(f"  missing on disk, skipped: {url}")
            continue
        with Image.open(src) as im:
            width = im.width
        candidates = []
        for w in WIDTHS:
            if width <= w * 1.1:  # not worth a rendition this close to the original
                continue
            out = src.with_name(f"{src.stem}-{w}.webp")
            if out.exists() and out.stat().st_mtime >= src.stat().st_mtime:
                kept += 1
            else:
                subprocess.run(
                    ["cwebp", "-quiet", "-q", QUALITY, "-m", "6", "-metadata", "none",
                     "-resize", str(w), "0", str(src), "-o", str(out)],
                    check=True,
                )
                made += 1
            candidates.append(f"{url.rsplit('/', 1)[0]}/{out.name} {w}w")
        if candidates:
            manifest[url] = ", ".join(candidates + [f"{url} {width}w"])

    body = json.dumps(manifest, indent=2, ensure_ascii=False)
    OUT_TS.write_text(
        "// GENERATED by scripts/make-image-variants.py — do not edit by hand.\n"
        "// Original image URL -> srcset listing its smaller WebP renditions and itself.\n"
        f"export const IMAGE_SRCSET: Record<string, string> = {body};\n",
        encoding="utf-8",
    )
    print(f"{len(manifest)} images with renditions; {made} written, {kept} up to date -> {OUT_TS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
